// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ7fbomUr8lW_bedLZxMS9OhknrR10Z64',
    appId: '1:958180968049:web:973b24dcea7a6ef72d7dd0',
    messagingSenderId: '958180968049',
    projectId: 'signemotion',
    authDomain: 'signemotion.firebaseapp.com',
    storageBucket: 'signemotion.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7HczzY2ekCuZBaCTZrvb9qICARcF_Nm8',
    appId: '1:958180968049:android:c97c5aaada72662f2d7dd0',
    messagingSenderId: '958180968049',
    projectId: 'signemotion',
    storageBucket: 'signemotion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUhlpQZKsoeUnicPM5D1L1sambw7Ll4AI',
    appId: '1:958180968049:ios:e903eb7da7c014cc2d7dd0',
    messagingSenderId: '958180968049',
    projectId: 'signemotion',
    storageBucket: 'signemotion.appspot.com',
    iosClientId: '958180968049-3j5evuo2i8c0eqqtvv00bh5m9s6te873.apps.googleusercontent.com',
    iosBundleId: 'com.example.signemotion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUhlpQZKsoeUnicPM5D1L1sambw7Ll4AI',
    appId: '1:958180968049:ios:e903eb7da7c014cc2d7dd0',
    messagingSenderId: '958180968049',
    projectId: 'signemotion',
    storageBucket: 'signemotion.appspot.com',
    iosClientId: '958180968049-3j5evuo2i8c0eqqtvv00bh5m9s6te873.apps.googleusercontent.com',
    iosBundleId: 'com.example.signemotion',
  );
}
